name: BackendPrep

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backendprep
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backendprep
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - db

volumes:
  pgdata:
