import { ANTHROPIC_AVAILABLE_MODELS_VALUES } from './anthropic/availableModels';
import { AVAILABLE_LLMS } from './availableLLMs';
import { GOOGLE_AVAILABLE_MODELS_VALUES } from './google/availableModels';
import { OPENAI_AVAILABLE_MODEL_VALUES } from './openai/availableModels';

export const ALL_MODEL_VALUES = [
  ...OPENAI_AVAILABLE_MODEL_VALUES,
  ...GOOGLE_AVAILABLE_MODELS_VALUES,
  ...ANTHROPIC_AVAILABLE_MODELS_VALUES,
];

export type AllModels = (typeof ALL_MODEL_VALUES)[number];

export const PROVIDER_MODEL_VALUES = {
  [AVAILABLE_LLMS.OPENAI]: OPENAI_AVAILABLE_MODEL_VALUES,
  [AVAILABLE_LLMS.GOOGLE]: GOOGLE_AVAILABLE_MODELS_VALUES,
  [AVAILABLE_LLMS.ANTHROPIC]: ANTHROPIC_AVAILABLE_MODELS_VALUES,
};
